name       : python-recommonmark
version    : 0.6.0
release    : 2
source     :
    - https://github.com/readthedocs/recommonmark/archive/0.6.0.tar.gz : d9aaeef3937e397794d8cd563c458f13d965ee22eb84732c9e214fa7ab8c9999
license    : MIT
component  : programming.python
summary    : A Python markdown parser for docutils 
description: |
    A docutils-compatibility bridge to CommonMark. This allows you to write CommonMark inside of Docutils & Sphinx projects.
rundeps    :
    - python-commonmark
    - python-sphinx
build      : |
    %python3_setup
install    : |
    %python3_install
