name       : python-recommonmark
version    : 0.7.1
release    : 4
source     :
    - https://github.com/readthedocs/recommonmark/archive/refs/tags/0.7.1.tar.gz : e5fb0f3965b86010976488589a45e48e9abb95101f2ddc2b3c31ca86d5261112
license    : MIT
component  : programming.python
summary    : A Python markdown parser for docutils
description: |
    A docutils-compatibility bridge to CommonMark. This allows you to write CommonMark inside of Docutils & Sphinx projects.
rundeps    :
    - python-commonmark
    - python-sphinx
build      : |
    %python3_setup
install    : |
    %python3_install
